spring:
  application:
    name: ddogdog
  profiles:
    active: secret
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

server:
  servlet:
    encoding:
      force: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
